# This is an example file you can use to deploy the blog to production using Docker compose.
# Obviously, it needs tweaking before it can be considered "ready".

services:
  blog:
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://bloguser:password@db:3306/blog
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mariadb:lts
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: blog
      MARIADB_USER: bloguser
      MARIADB_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
